image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "1"
  
services:
  - docker:19.03.1-dind

before_script:
  - apk update
  - apk add docker-compose make curl bash git
  
stages:
  - development
  - release

development:
  stage: development
  script:
    - make build
    - make tests
  tags:
    - docker
    - eros
    - lcmap
  except:
    - tags

release:
  stage: release
  script:
    - make build
    - make tests
    - make deploy
  tags:
    - docker
    - eros
    - lcmap
  only:
    - tags